### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by chrisk314** [auth0-samples/auth0-golang-api-samples#32]
Attempting to run the example with the commands provided in the instructions fails.

Firstly `go get -d` fails as there is no `go.mod` file.

The `go.mod` file should be as below

```
module main

go 1.15

require (
	github.com/auth0/go-jwt-middleware v1.0.0
	github.com/codegangsta/negroni v1.0.0
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/gorilla/mux v1.8.0
	github.com/joho/godotenv v1.3.0
	github.com/rs/cors v1.7.0
)
```

After installing the requirements, attempting to run the example code with `go run main.go` fails with the below error

```
$ go run main.go 
# command-line-arguments
./main.go:45:3: cannot use func literal (type func(*"github.com/dgrijalva/jwt-go".Token) (interface {}, error)) as type "github.com/form3tech-oss/jwt-go".Keyfunc in field value
```

**Comment by chrisk314** [comment]
Issue was caused by outdated dependency. `github.com/dgrijalva/jwt-go v3.2.0+incompatible` should be `	github.com/form3tech-oss/jwt-go v3.2.2+incompatible`. Fixed by #33.

**Comment by majochoc** [comment]
This example is still broken, and the above fix is no longer applicable.
